packages:
  - packages/*

catalogs:
  website:
    "@biomejs/biome": 2.2.5
    "@tailwindcss/vite": 4.1.14
    astro: 5.14.1
    gh-pages: 6.3.0
    markuplint: 4.13.1
    modern-normalize: 3.0.1
    tailwindcss: 4.1.14
  yama-normalize:
    "@eslint/css": 0.11.1
