packages:
  - packages/*

catalogs:
  website:
    "@biomejs/biome": 2.3.3
    "@tailwindcss/vite": 4.1.16
    astro: 5.15.3
    gh-pages: 6.3.0
    markuplint: 4.13.1
    modern-normalize: 3.0.1
    tailwindcss: 4.1.16
  yama-normalize:
    "@eslint/css": 0.14.1
