onlyBuiltDependencies:
  - "@biomejs/biome"
  - es5-ext
  - esbuild
  - sharp

overrides:
  yamanoku.github.io>vite: ^8.2.1

packageExtensions:
  "@eslint/css":
    peerDependencies:
      "@types/css-tree": 2.3.10

allowBuilds:
  esbuild: true
  sharp: true

packages:
  - packages/*
  - records
  - records/presentations

catalogs:
  website:
    "@biomejs/biome": 2.5.10
    "@tailwindcss/vite": 4.3.3
    astro: 7.2.2
    markuplint: 4.18.3
    modern-normalize: 3.0.1
    tailwindcss: 4.3.3
    vite: 8.2.1
  yama-normalize:
    "@eslint/css": 1.4.0
  presentations:
    "@11ty/eleventy": 3.1.6
    "@iconify-json/twemoji": 1.2.5
    "@iconify-json/vscode-icons": 1.2.75
    "@slidev/cli": 52.19.1
    "@slidev/client": 52.19.1
    "@slidev/theme-apple-basic": 0.25.1
    "@slidev/theme-default": 0.25.0
    "@slidev/types": 52.19.0
    budoux: 0.9.0
    highlight.js: 11.12.0
    markdown-it: 14.3.0
    markdown-it-footnote: 4.0.0
    vue: 3.5.41
