packages:
  - packages/*

catalogs:
  website:
    "@biomejs/biome": 2.4.9
    "@tailwindcss/vite": 4.2.2
    astro: 6.0.8
    gh-pages: 6.3.0
    markuplint: 4.14.1
    modern-normalize: 3.0.1
    tailwindcss: 4.2.2
  yama-normalize:
    "@eslint/css": 1.0.0
