packages:
  - packages/*

catalogs:
  website:
    "@biomejs/biome": 2.4.6
    "@tailwindcss/vite": 4.2.1
    astro: 6.0.4
    gh-pages: 6.3.0
    markuplint: 4.14.1
    modern-normalize: 3.0.1
    tailwindcss: 4.2.1
  yama-normalize:
    "@eslint/css": 0.14.1
