contact_links:
  - name: Discussions
    url: https://github.com/yamanoku/yamanoku.github.io/discussions
    about: Issueにするほどでもない提案・雑談をするときに活用してください
  - name: X (formerly Twitter)
    url: https://twitter.com/yamanoku
    about: X (旧 Twitter) で直接連絡する（反応しやすいです）
