<template>
  <section id="book">
    <h2>著書</h2>
    <h3>これからはじめるwebアクセシビリティ</h3>
    <figure>
      <img
        src="~/assets/img/product-web-accessibility-for-beginner.jpg"
        :alt="$t('prefixAlt.photo') + $t('product.wafb.title')"
      />
      <figcaption>
        <p>
          技術書典で「これからはじめるwebアクセシビリティ」という技術同人誌を発表しました。Webアクセシビリティをはじめる方向けの導入として知ってもらいたいのがきっかけでした。
        </p>
        <p>現在BOOTHやNoteでもPDFファイルにて販売しております。</p>
        <ul>
          <li>
            <a
              href="https://booth.pm/ja/items/1044446"
              target="_blank"
              rel="noopener"
              >これからはじめるwebアクセシビリティ - こんのいぬ -
              BOOTH<open-new-icon
            /></a>
          </li>
          <li>
            <a
              href="https://note.mu/yamanoku/n/n3487a344ff84"
              target="_blank"
              rel="noopener"
              >「これからはじめるwebアクセシビリティ」をnoteにて販売します｜Okuto
              Oyama｜note<open-new-icon
            /></a>
          </li>
        </ul>
        <p>
          またGitHubのフィードバック用のリポジトリのIssueにて修正や改善、提案を受け入れています。
        </p>
        <a
          href="https://github.com/yamanoku/accessibility_book-issues"
          target="_blank"
          rel="noopener"
          >yamanoku/accessibility_book-issues:
          「これからはじめるwebアクセシビリティ」へのFB専用リポジトリ<open-new-icon
        /></a>
      </figcaption>
    </figure>
  </section>
</template>
