name: ESLint

on:
  pull_request:
    branches:
      - dev
      - yarn-v4
    paths:
      - "**.ts"
      - "**.astro"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: corepack enable
    - run: yarn set version stable
    - name: check eslint
      run: |
        yarn install
        yarn eslint
      env:
        CI: true
